### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by CoryArrow** [analogdevicesinc/aditof_sdk#1]
When trying to build the kernel and rootfs for the Dragonboard following the steps detailed in [dragonboard_firmware_build.md](https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/dragonboard_firmware_build.md), I am unable to clone the kernel with the following command:
`git clone https://github.com/adi-sdg/dragonboard_410c_kernel.git`

I receive the following error message:

> remote: Repository not found.
fatal: repository 'https://github.com/adi-sdg/dragonboard_410c_kernel.git/' not found

When I navigate to url above, there are no public repositories to be clone. The same error exists if I try to run the [db410c_get_kernel_rootfs_dependencies.sh](https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/scripts/host_setup/db410c_get_kernel_rootfs_dependencies.sh) script, obviously because the script points to the same repository location.

Can you please update the instructions to point to a public repository where I can clone the kernel?

Thanks!

-Cory

**Comment by dNechita** [comment]
This has been solved with https://github.com/analogdevicesinc/aditof_sdk/pull/4
