### ISSUE TITLE
can you provide calibration tool for depth value？

### ISSUE THREAD

**Issue by KirkKong** [analogdevicesinc/aditof_sdk#151]
can you provide calibration tool or method for depth value？

**Comment by dNechita** [comment]
The value of each element of a frame is depth. The unit is mm.

**Comment by KirkKong** [comment]
> The value of each element of a frame is depth. The unit is mm.

@dNechita
Thanks for your reply!
I mean how to create the calibration data stored in EEPROM, such as Gain and Offset.
Do you have user guide or calibration tool?

**Comment by acozma** [comment]
The calibration software and user guide is currently in the final development stage and it will be released in the next few weeks.

**Comment by KirkKong** [comment]
> The calibration software and user guide is currently in the final development stage and it will be released in the next few weeks.

@acozma 
Thanks a lot!
I will pay attention to the changes in the next few weeks.

**Comment by dNechita** [comment]
The calibration software is available.
Doc is at: https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/calibration
