### ISSUE TITLE
Start network server on target by pressing S4

### ISSUE THREAD

**Issue by acozma** [analogdevicesinc/aditof_sdk#165]
Start network server on target by pressing S4 on the ToF camera board.
The red DS5 led should light up when the server starts.
USB and ETH are mutually exclusive.

**Comment by DanielGuramulta** [comment]
Should investigate if we could start the network server by default.

**Comment by dNechita** [comment]
Check auto-detection on network.

**Comment by dNechita** [comment]
Start server by default on all targets.
