### ISSUE TITLE
Demo: failed to get frames after toggling the noise reduction in far mode

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#184]
This is while capturing frames.
Seen it happen on target and over USB.

**Comment by DanielGuramulta** [comment]
On far mode the option to set the noise reduction value should be disabled (It does not apply for far mode)

**Comment by grigorovici-andreea** [comment]
Because of hardware limitations, noise reduction does not work in far mode. 
This should be disabled from the sdk.
