### ISSUE TITLE
Demo: why use a reduced color map for medium and far modes

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#185]
The depth is mapped to colors, spanning from red to magenta.
In medium and far modes, the minimum length that can be measured is higher than in near mode but for these minimum values we don't start mapping from red.
So, the color map should be adjusted to the measuring interval. The red should correspond to the lowest measurement value no matter which mode is enabled.

**Comment by grigorovici-andreea** [comment]
The minum range of the system:
              Theory                                                  Real
Near - 250 mm                                        ||     0 mm
Medium - 300 mm (RevB: 800 mm)        ||     390 mm
Far - 3000 mm                                         ||     2000 mm
