### ISSUE TITLE
Update the instructions on how to unpack the SD card image

### ISSUE THREAD

**Issue by acozma** [analogdevicesinc/aditof_sdk#196]
The latest SD card image archive was compressed using xz. The unpack instructions [here](https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/sdcard_burn.md) must be updated since this compression method will be used from now on.

Also, need to add .img extension to the file that's in the xz archive.

**Comment by dNechita** [comment]
The SD card images have been updated. Closing this.
