### ISSUE TITLE
Demo: Missing #include <string> in system_impl.h of aditof C++ project

### ISSUE THREAD

**Issue by mockingjay14** [analogdevicesinc/aditof_sdk#207]
Problem: Unable to do building of aditof demo project in C++ despite doing default installation. Arising errors are shown in image below. 
<img width="797" alt="Error" src="https://user-images.githubusercontent.com/60774171/74212966-e6aa0780-4cd1-11ea-8755-ef87999fe85d.png">

Solution: Place `#include <string>` in the **system_impl.h** file located in the external dependencies of aditof project. 
<img width="778" alt="Solution" src="https://user-images.githubusercontent.com/60774171/74213162-f83fdf00-4cd2-11ea-8789-3de276b541ae.png">

**Comment by dNechita** [comment]
You are right, thanks for reporting this.
We will add a fix.

**Comment by dNechita** [comment]
Just out of curiosity, what compiler (and which version) did you use?
Thanks!

**Comment by mockingjay14** [comment]
@dNechita I used Visual Studio 16 2019, Visual C++ v14.24.

**Comment by dNechita** [comment]
Thanks!
