### ISSUE TITLE
Create wiki page for Calibration Guide

### ISSUE THREAD

**Issue by grigorovici-andreea** [analogdevicesinc/aditof_sdk#215]

**Comment by grigorovici-andreea** [comment]
https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/calibration

**Comment by dstockhouse** [comment]
Hi, I'm using the ADI ToF eval kit for a university capstone project. The link to the calibration wiki above leads me to an error page. Has the page moved or been made non-public?
Thanks,
David

**Comment by dNechita** [comment]
Hi David,

The page on the wiki website is currently under review and will be made public soon.
It's mostly based on the old doc: https://github.com/analogdevicesinc/aditof_sdk/blob/master/tools/calibration-96tof1/Calibration_Guide%20v2.pdf

**Comment by dNechita** [comment]
Hi @dstockhouse 

The wiki page is now available at:
https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/calibration

**Comment by dstockhouse** [comment]
Thank you!
