### ISSUE TITLE
MATLAB Adaptor build broken

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/aditof_sdk#237]
See here: https://gitlab.com/tfcollins/TimeofFlightToolbox/-/jobs/461639926#L4601

Looks like the aditof::CameraDetails struct changed.

**Comment by DanielGuramulta** [comment]
Will have a look at the issue, and fix it as soon as possible.

Thanks for reporting it.

**Comment by tfcollins** [comment]
@DanielGuramulta I'll add a daily build against master for MATLAB
