### ISSUE TITLE
Add support for Jetson Nano

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#258]
Also add doc page for this.

**Comment by tamaslevente** [comment]
Please check the server (RPI4) setup connectivity with Jetson client (unable to connect using the libwebsocket built locally on Jetson).

**Comment by dNechita** [comment]
Does ping work between Jetson and RPI4? Also can you ssh from Jetson to RPI4?

**Comment by tamaslevente** [comment]
Ping/ssh works, it was a proxy issue set on the jetson (ssl seems to
generate some problem through proxy).

Dan Nechita <notifications@github.com> ezt írta (időpont: 2020. ápr. 24.,
P, 15:23):
