### ISSUE TITLE
DB410C Script to Write ToF Board EEPROM

### ISSUE THREAD

**Issue by CoryArrow** [analogdevicesinc/aditof_sdk#26]
Hello,

I have flashed and booted my DB410C using the supplied image ([aditof-v0.2-dragonboard410c-sdimage.tar.xz](http://swdownloads.analog.com/cse/aditof/aditof-v0.2-dragonboard410c-sdimage.tar.xz)), however when I attempt to run the aditof_demo.sh script on the desktop, the console provides the following message:

`W0603 17:56:29.832276 6052 camera_impl.cpp:81] Failed to read firmware from eeprom`

I am NOT using a production board and it is my understanding that these boards do not have the required factory calibration info written to the EEPROM. I was informed that @acozma may have an executable that can run on the DB410C to write to the EEPROM to make these pre-production boards usable. @acozma can you please provide the executable for writing to the EEPROM?

Thanks,

Cory

**Comment by dNechita** [comment]
We will not support pre-production boards on github.
