### ISSUE TITLE
Maskr-cnn python

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#262]

**Comment by grigorovici-andreea** [comment]
Some intermediate results. 

![image](https://user-images.githubusercontent.com/54316691/78105541-133cee80-73fa-11ea-9a12-b85fd99c0858.png)

**Comment by grigorovici-andreea** [comment]
Investigation results:

- we need to give access to 3 configuration files: **COCO object class LABELS**, **TENSOFLOW model configuration files, based on COCO dataset**: _frozen_inference_graph.pb and mask_rcnn_inception_v2_coco_2018_01_28_ 
We can either give access directly to the files, by adding them in our repo or give the user the following link from where they can use the script to get access to any model:(https://github.com/opencv/opencv_extra/blob/master/testdata/dnn/download_models.py).

- the results are reasonable good:
![person_maskrcnn](https://user-images.githubusercontent.com/54316691/78748956-e34f9700-7975-11ea-977a-31dff07719c0.PNG)

- for real-time processing and results using mask-RCNN is not feasible as the time for processing a frame is around 1.50 seconds:
![time](https://user-images.githubusercontent.com/54316691/78748913-d3d04e00-7975-11ea-913c-d87182d2d109.PNG)
 * the time for processing a frame si not influenced by our data, any picture I gave to the script the time did not improve. 
 * also checked by getting a video from youtube to be processed, the same result:
![time_in_video](https://user-images.githubusercontent.com/54316691/78749188-6a9d0a80-7976-11ea-9a95-a41155b96bae.PNG)
