### ISSUE TITLE
Error: "No matching distribution found for open3d"

### ISSUE THREAD

**Issue by arrowperfecto** [analogdevicesinc/aditof_sdk#283]
Using image released to support resolving issue [#217](https://github.com/analogdevicesinc/aditof_sdk/issues/217) .  I’ve done some test, there is no more issue with the import of the opencv python module so I was able to play a little bit with the camera.
I’ve tried the [showPointCloud](https://github.com/analogdevicesinc/aditof_sdk/tree/master/bindings/python/examples/showPointCloud) and this time it’s with the import of the open3d module that I have a problem, I tried to install it (sudo pip install opend3d, sudo pip3 install opend3d) but I’ve got an error message “No matching distribution found for open3d”, do you have any advice to solve this issue?
Thank you.

**Comment by dNechita** [comment]
The open3D python module is not provided via PyPi.
One option is to compile open3D (including the python3 module) from source.
We can look into this and add it to the image. However, it's possible that open3d example will run very slow on the embedded target (maybe I'm wrong).
