### ISSUE TITLE
Problem with "USB bridge" under Linux (Ubuntu in a virtual machine)

### ISSUE THREAD

**Issue by arrowperfecto** [analogdevicesinc/aditof_sdk#284]
Using image released to support resolving issue [#217](https://github.com/analogdevicesinc/aditof_sdk/issues/217).  I’ve also tried to use the “usb bridge” under linux (Ubuntu in a virtual machine): 
The camera is recognized by the pc:
![screen1](https://user-images.githubusercontent.com/45641619/77985314-610a0780-72d1-11ea-9ce9-64163fb0dba5.png)
I tried the script “first_frame.py”, the initialization seems ok but it failed to get a frame…  
![screen2](https://user-images.githubusercontent.com/45641619/77985350-797a2200-72d1-11ea-876b-62ed5e0667c9.png)
Are you aware of this kind of issue under linux (and/or with a virtual machine)?
Thank you.

**Comment by dNechita** [comment]
Hi,
On what host is the Virtualbox running? Is it Windows 10?

**Comment by arrowperfecto** [comment]
Yes, it’s windows 10

**Comment by dNechita** [comment]
I didn't encountered this error before. Things should work on Linux (non VM).
Also things should work on linux virtual machines (mostly Ubuntu and Debian) but the difference is that the host was an Ubuntu 18.04 not Windows. (using Virtual Machine Manager)

**Comment by dNechita** [comment]
I did some tests using VirtualBox on Windows with a Ubuntu 18.04 VM. The USB communication is pretty unstable and examples don't work.
I don't recommend using this type of setup.
