### ISSUE TITLE
Create SD card for Nvidia Jetson

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#292]
And add build instructions, similar to the ones on other platforms.
E.g. https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/dragonboard410c/build_instructions.md

**Comment by KamelAbdelouahab** [comment]
Hello all, 

May I know the status of this ? I followed the instructions [here](https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/ug_jetson) but without any success. A pre-built image to burn on an SD card would so much practical. 

Thanks,
Kamel

**Comment by dNechita** [comment]
We've started work on this, should be done by the end of this week.

**Comment by KamelAbdelouahab** [comment]
Thanks for the image. I will be testing it today !
