### ISSUE TITLE
open3d/showPointCloud Add depth correction before creating pointcloud

### ISSUE THREAD

**Issue by grigorovici-andreea** [analogdevicesinc/aditof_sdk#297]
Add the correction, then test with the chessboard to see the results.

**Comment by dNechita** [comment]
Doing this in the SDK #317 should solve things and correction would not be required in the Open3D bindings.

**Comment by grigorovici-andreea** [comment]
Branch: https://github.com/analogdevicesinc/aditof_sdk/tree/open3D-depth_correction has a working version of the correction application. This branch will be used as a testing reference when #317 is working. Afterward can be closed.
