### ISSUE TITLE
execute the Setup.sh scripts to proceed Linux setup fails

### ISSUE THREAD

**Issue by grigorovici-andreea** [analogdevicesinc/aditof_sdk#303]
* based on provided link: https://github.com/analogdevicesinc/aditof_sdk/tree/master/scripts/linux |   
* execute the Setup.sh  scripts to proceed Linux setup (use ubuntu   16.04 LTS)

![image](https://user-images.githubusercontent.com/54316691/79125506-fe237080-7da6-11ea-9559-8d08b9aa7fc7.png)

* have confirmed installed package(glog+protobuf+websockets+ros), any Linking error occurred, almost are from google::protobuf,  libaditof.so.1.3.0  undefined reference to google::protobuf.

![image](https://user-images.githubusercontent.com/54316691/79125661-2f03a580-7da7-11ea-900a-0cff4d5fb415.png)

**Comment by grigorovici-andreea** [comment]
The problem might be that the script is downloading opencv by itself and the one that is already is system is interfering, please use the option --buildopencv  when running the script.  The script will download, build and install version 3.4.1 of opencv if the argument “—buildopencv” is given. Also before re-running the script, please delete the files already created by the script.

**Comment by s9323249** [comment]
1.Delete the files already created by the script.
2.Re-running the script
**./setup.sh -bo**

get the error,
![Screenshot from 2020-04-14 15-52-50](https://user-images.githubusercontent.com/63579578/79199756-04c5ec80-7e68-11ea-8873-afa39a6638ef.png)

**Comment by grigorovici-andreea** [comment]
Hello,

Can you please tell what Kernel do you have on your ubuntu? 

Also, when you first run the script can you tell us the output you receive, we need to know which protobuf is found by CMAKE. 

Also, do you know if you installed before protobuf using apt-get?

Thank you

**Comment by s9323249** [comment]
Can you please tell what Kernel do you have on your ubuntu?
**>>4.15.0-96-generic** 

when you first run the script can you tell us the output you receive, we need to know which protobuf is found by CMAKE.
**>> please see attachment files. (log,txt)**

 do you know if you installed before protobuf using apt-get? 
**>>Only using script install.**


[log.txt](https://github.com/analogdevicesinc/aditof_sdk/files/4484488/log.txt)

**Comment by grigorovici-andreea** [comment]
Hello,

We tried on a virtual machine and the script should work. 
In order to figure out the problem, can you please try to build the project using the building steps from here and let us know if any problem appears and where: **https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/linux/build_instructions.md.**

**Comment by s9323249** [comment]
Dear,
I setp by step installation,and the screenshot,
**Glog:**
![glog](https://user-images.githubusercontent.com/63579578/79957684-8646fb80-84b4-11ea-8d8a-c2dd905a14d1.png)
**Libwebsockets:**

![
    Libwebsockets](https://user-images.githubusercontent.com/63579578/79957719-96f77180-84b4-11ea-844d-2b6ca718a9eb.png)

**protobuf:**

![protobuf](https://user-images.githubusercontent.com/63579578/79957761-a971ab00-84b4-11ea-86e3-cf8557fb7d45.png)

**Download and build SDK only**
> make
an error appears,

![build sdk error](https://user-images.githubusercontent.com/63579578/79957877-d45bff00-84b4-11ea-9204-9fae56304202.png)

**Comment by grigorovici-andreea** [comment]
Hello,

As we cannot reproduce your problem, we ask you kindly to try again on a clean set up.
It looks like the dependencies are correct, but our only guess is that they interfere with something that was already installed on your system.
 Do you have the possibility to do the steps on a clean set-up? (that means on a new Linux where you do not have installed everything yet).

Also please make sure you clone the latest version from the aditof sdk repository.

**Comment by s9323249** [comment]
Dear,
thanks for your advice, i try a new Linux ubuntu 18.04,
and it can be compiled.
and run the example  aditof- demo ,an error appears,
![Screenshot from 2020-05-04 11-48-32](https://user-images.githubusercontent.com/63579578/80937809-339d0600-8e09-11ea-804f-c013affb27a1.png)

can you give some advice,thanks.

**Comment by grigorovici-andreea** [comment]
Hello,

Do you have the camera connected through USB?
Can you check if your system recognize the camera? (use dmesg command in a new terminal, should appear under the name ADITOF DEPTH SENSOR).

Also, you can choose the connection you want with the camera (USB/Ethernet) by using the first checkbox.

Thank you?

**Comment by s9323249** [comment]
hi,
thanks for your advice.
First i check the device can  correct work on windows 10 ,
![S__48398338](https://user-images.githubusercontent.com/63579578/81382250-ad522e00-9140-11ea-985d-31fab66fc8fc.jpg)
![S__48398340](https://user-images.githubusercontent.com/63579578/81382257-af1bf180-9140-11ea-8968-6ee9563d36d4.jpg)

and then run on Ubuntu system ,use dmesg command,
![Screenshot from 2020-05-08 15-22-45](https://user-images.githubusercontent.com/63579578/81382364-d8d51880-9140-11ea-8ff9-8c8ce19ea0dd.png)

**Comment by s9323249** [comment]
hi,
Do you have the camera connected through USB?
**>>Yes**
Can you check if your system recognize the camera? (use dmesg command in a new terminal, should appear under the name ADITOF DEPTH SENSOR).

**Comment by grigorovici-andreea** [comment]
Hello,

It looks like the ADITOF DEPTH SENSOR is nor recognized by your system.

Please see our documentation from here: _https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/ug_linux_, the section **Enable the USB connection to the host PC**.

Thank you

**Comment by grigorovici-andreea** [comment]
Hello @s9323249,

Did you succeed with the project? 

Is anything else we can help you with for this ticket? 

Thank you

**Comment by s9323249** [comment]
Hello,
thanks for your advice.
Now having some problems,
Hardware :  Raspberry Pi 4 + chicony Tof
![S__48922629](https://user-images.githubusercontent.com/63579578/82402172-5b899c00-9a8e-11ea-9a21-46ecfe1d993e.jpg)

Through the interface USB3.0 connect   Raspberry Pi 4 + chicony Tof

And using  Lasest SD card image

![image](https://user-images.githubusercontent.com/63579578/82402307-a86d7280-9a8e-11ea-94ee-6231a033c369.png)

Run the Aditof-Demo
![S__48922627](https://user-images.githubusercontent.com/63579578/82402469-039f6500-9a8f-11ea-9b32-dfeb66b526b8.jpg)
![S__48922630](https://user-images.githubusercontent.com/63579578/82402474-0732ec00-9a8f-11ea-8fe2-3656e11bf16e.jpg)


But Can't find camera,can you give some advice for USB3.0 method,thanks.

**Comment by dNechita** [comment]
Hi,

 As you can see in the log messages of the aditof-demo, it looks for the device (camera) on the target (MIPI connection).
To make it look for the devices connected on USB, you need to make sure you are building the entire project for a remote PC and not for a target. This is done when generating the build system with CMake.
Create a new build folder or delete the existing one then create an empty build folder. The run cmake but don't specify the target (don't add -DRASPBERRYPI=1 in the cmake command).

We haven't tried this on a target before, in theory it should work.

**Comment by s9323249** [comment]
Hello,
thanks for your advice.
but we would like to know why we need to build entire project in PC rather than on the rasp, than currently we meet the error like the below: we run cmake command after delete build folder 

![S__49102850](https://user-images.githubusercontent.com/63579578/82627120-2f9c2100-9c1c-11ea-8f2d-b1691d21f4e6.jpg)

could you help us to solve this problem...thx.

**Comment by dNechita** [comment]
There are 2 modes when you build the project: 'remote mode' and 'target mode' (The target mode is when you define a target on the cmake command, e.g. cmake -DRASPBERYPI=1. If you don't then the mode will be remote-mode). 
On the 'remote-mode' the project expects that camera are accessible through some channels of communication (USB and Ethernet).
On 'target-mode' the project expects that the camera is available on the system of the target (through MIPI connection).
You don't have to build the project (in remote-mode) only on PC, it can be done on RPI or other platforms that operate with a Linux distribution). It's just that the common scenario is to build it on a PC.

Regarding you build issue:
You need to tell CMake where to look for Glog, Protobuf and Websockets. It looks you have them at path:
/home/pi/workspace/github/aditof_sdk/deps/installed
So replace the paths referring to /opt.
E.g.
`DCMAKE_PREFIX_PATH="/home/pi/workspace/github/aditof_sdk/deps/installed/glog;/home/pi/workspace/github/aditof_sdk/deps/installed/protobuf;/home/pi/workspace/github/aditof_sdk/deps/installed/websockets"`
