### ISSUE TITLE
EEPROM upgrade tool

### ISSUE THREAD

**Issue by acozma** [analogdevicesinc/aditof_sdk#364]

**Comment by bitslip6** [comment]
would be nice to just hexdump -v /sys/class/i2c-dev/i2c-1/device/1-0056/eeprom and then parse and write back.  or perhaps even just:
"cat /sys/class/i2c-dev/i2c-1/device/1-0056/eeprom > firmware.bin"
"cat firmware.bin >/sys/class/i2c-dev/i2c-1/device/1-0056/eeprom"
