### ISSUE TITLE
Problems with imshow example compiling

### ISSUE THREAD

**Issue by littleyueh** [analogdevicesinc/aditof_sdk#387]
Hi, 

I want to add some extra functions on the /bindings/opencv/imshow/main.cpp, and compile it to a .exe file for me
So I download the image file (for Rpi system), copy the /workplace/aditof_sdk to desktop, and rewrite the main.cpp

then I go to /Desktop/aditof_sdk to run the cmake command, want to build a .exe file just like /build/bindings/opencv/imshow/aditof-opencv-show

but it returns the following error message: Could not found protobuf
![image](https://user-images.githubusercontent.com/32427911/87564420-f56a6f80-c6f2-11ea-9e57-befe467660d1.png)

I saw the document said the image file has all the dependencies package.
Should I re-download the protobuf package again?

I will appreciate any help and advice, thanks

**Comment by littleyueh** [comment]
Hi,

I've changed my cmake command and the following is the result:
![image](https://user-images.githubusercontent.com/32427911/87626292-98a49e80-c75e-11ea-987c-b3e12891d94a.png)

The configuration is done, but when I tried to build, it stuck on the step of building "device_enumerator_ethernet.cpp.o"
I checked the /aditof_sdk/sdk/src/connections/network, there is no such header file called "buffer.pb.h"

I will appreciate any help and advice, thanks

**Comment by dNechita** [comment]
Hi,

We had this fixed recently.
Can you try with the latest master branch?

**Comment by littleyueh** [comment]
Hi @dNechita 

I got it
It works, thanks!

**Comment by dNechita** [comment]
Glad to hear that!
If you are disabling the network support then you no longer need the following dependecies: websockets and protobuf (no need to add their paths to CMAKE_PREFIX_PATH)

Closing this.
