### ISSUE TITLE
RPi4 boot configuration

### ISSUE THREAD

**Issue by mu1492** [analogdevicesinc/aditof_sdk#518]
I am trying to boot a Raspberry Pi 4 model B (8GB RAM) with ADI's custom kernel.

Firstly, I flashed on the SD card an image given [here](http://swdownloads.analog.com/cse/aditof/raspberrypi-latest-image.tar.xz) - link can be accessed via [https://github.com/analogdevicesinc/aditof_sdk](https://github.com/analogdevicesinc/aditof_sdk), under 96-TOF1-EBZ. The device does not boot, it remains at the four raspberries in a row screen.

Secondly, I was building the `kernel7l.img` file, as described [here](https://wiki.analog.com/resources/tools-software/linux-build/generic/raspberrypi), under manual cross-compiling.
- the **rpi-4.14.y** branch does not contain `adi_bcm2711_defconfig` under `./arch/arm/configs/`, which is required for RPi4, therefore two valid options I found are branches **rpi-4.19.y** and **rpi-5.4.y**. 
- RPi 4 does not boot with `kernel7l.img` built from branch rpi-4.19.y
- RPi 4 boots with `kernel7l.img` built from branch rpi-5.4.y

Please verify and update notes accordingly, since it appears that only branch **rpi-5.4.y** provides a valid boot for RPi 4.

**Comment by SeptimiuVana** [comment]
The error cannot be reproduced.
