### ISSUE TITLE
Log sdk version and current commit 

### ISSUE THREAD

**Issue by VLitanADI** [analogdevicesinc/aditof_sdk#523]
Log the sdk version (major.minor.patch) and the current commit hash at every run

**Comment by dNechita** [comment]
and branch

**Comment by tmanalog** [comment]
Is this format ok?
I1116 11:10:04.802145 23804 system_impl.cpp:111] SDK version -> 3.0.0, branch -> master, commit -> 0eabf2e63c917eae8a5fde4862d2cb2d993f9ee3
