### ISSUE TITLE
XavierNX device tree and cam-i2c-mux

### ISSUE THREAD

**Issue by KamelAbdelouahab** [analogdevicesinc/aditof_sdk#567]
Hi all,

We are working with an FX-TOF camera and a XavierNX, and we would like to attach a second (non ToF) camera on the second CSI port on the devkit. 

The `cam_i2cmux` part is giving us troubles as the two only available entries are occupied by the ToF camera. Knowing that Nvidia uses a 2->1 i2c mux in their devkit, we managed to successfully register the two cameras (3 i2c devices) by bypassing the mux for camera 2 (we can provide the full dts if needed): 

```
cam_i2cmux {
		compatible = "i2c-mux-gpio";
		#address-cells = <1>;
		#size-cells = <0>;
		i2c-parent = <&cam_i2c>;
		mux-gpios = <&tegra_aon_gpio CAM_I2C_MUX GPIO_ACTIVE_HIGH>;
		i2c@0 {
               // ADI ToF
		};
		i2c@1 {
               // ADI IR
		};
};
i2c@3180000 {
		#address-cells = <1>;
		#size-cells = <0>;	
		status = "okay";
                // Camera 2 scope ...
};
```

However, it's impossible to capture frames from both devices simultaneously as one device occupies the hole bus during capture. FX-TOX addresses are not acknowledged  while camera 2 is being used and vice versa ...

Is it possible to implement the ADDI with only one i2c entry? Otherwise, can we use other I2Cs in a way to keep one mux entry for other cameras ? 

Thanks for your assistance,

**Comment by KamelAbdelouahab** [comment]
Update: 
We placed ADI_IR on another i2c (the one that goes to the GPIO expander). It seems to work fine.

**Comment by dNechita** [comment]
Thanks for sharing the solution. Glad to hear that things worked out.
