### ISSUE TITLE
Update user guides to point people to our SD card images first

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#598]
User guides are probably on wiki.analog.com
Some user  guides (I think the Jetson + FXTOF1 but check for others as well) are describing how to build the kernel, divers, device tree and other things. And this is in the beginning of the page so it might happen that some people don't get to the part where we mention that a SD card image already exists and there is no need for the complicated things to be done.

**Comment by SeptimiuVana** [comment]
Documentation added for the following wiki pages:
* https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/ug_jetson
* https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/ug_xavier_nx
* https://wiki.analog.com/resources/eval/user-guides/ad-96tof1-ebz/ug_xavier_agx
* https://wiki.analog.com/resources/eval/user-guides/ad-fxtof1-ebz/ug_jetson
* https://wiki.analog.com/resources/eval/user-guides/ad-fxtof1-ebz/ug_xavier_nx
