### ISSUE TITLE
Raspberry Pi3 - Jumper Settings  JP1

### ISSUE THREAD

**Issue by bitslip6** [analogdevicesinc/aditof_sdk#60]
In the raspberry pi documentation it says to short Pins 2 and 3 on JP1.

JP1 comes factory set to short pins 1 and 2.

Is the correct setting for Raspberry Pi shorted pins 1 2 and 3 or only pins 2 and 3?

Thank you so much for your help!

**Comment by dNechita** [comment]
Only pins 2 and 3.
