### ISSUE TITLE
Add96tof1: make setFrameType functional for frame type changes

### ISSUE THREAD

**Issue by rbudai98** [analogdevicesinc/aditof_sdk#698]

**Comment by dNechita** [comment]
Well, setFrameType function is available on target and on network. It has been for a long time.
This is where setFrameType is implemented in Camera96TOF1:
https://github.com/analogdevicesinc/aditof_sdk/blob/master/sdk/src/cameras/ad-96tof1-ebz/camera_96tof1.cpp#L366
And this is the Network implementation:
https://github.com/analogdevicesinc/aditof_sdk/blob/master/sdk/src/connections/network/network_depth_sensor.cpp#L280
And this is the Target implementation:
https://github.com/analogdevicesinc/aditof_sdk/blob/master/sdk/src/connections/target/addi9036_sensor.cpp#L355

So the title of this issue should be changed as it creates confusion.

**Comment by rbudai98** [comment]
Done
