### ISSUE TITLE
Need information about tools available to generate and program calibration data

### ISSUE THREAD

**Issue by Radhika-Sekar** [analogdevicesinc/aditof_sdk#71]
Hi ,

I am working with AD-96TOF1-EBZ board with latest sdcard image available in the following link swdownloads.analog.com/cse/aditof/aditof-v0.2-dragonboard410c-sdimage.tar.xz.

By understanding the SDK source code, i have found calibration data is programmed to EEPROM available in 96tof1 camera board. But i didn't find any tool to program the calibration data both in this github and AD-96TOF1-EBZ board product page.

Can someone help me to find the tool to program the calibration data ?

And also it would be helpful if someone explains in brief about how calibration data is generated ?

Thanks

**Comment by acozma** [comment]
Hi,

Each board is calibrated on the production line and calibration data is programmed into the EEPROM at that time. The calibration API is [here](https://github.com/analogdevicesinc/aditof_sdk/blob/master/sdk/src/calibration.h) but there are no tools to program the calibration data.

The calibration data is a collection of [register address, register value] pairs that are being generated during the factory calibration process. The calibration procedure is not yet public but we are working on making in public in the next month or so.

Is there a specific reason why you need to program the EEPROM with calibration data?

Thanks,
Andrei
