### ISSUE TITLE
correct calculation for distance value

### ISSUE THREAD

**Issue by bitslip6** [analogdevicesinc/aditof_sdk#74]
Trouble reading depth data.

After running first-frame I am having difficulty figuring out the depth data.   After reading though aditofdemoview.cpp I modified the first-frame code to the following:

```
    FrameDetails fDetails;
    frame.getDetails(fDetails);
    cv::Mat m_depthImage = cv::Mat(fDetails.height/2, fDetails.width, CV_16UC1, data1);
    cv::Point2d pointxy(320, 240);


    int m_distanceVal = m_depthImage.at<ushort>(pointxy);
    //m_distanceVal = static_cast<int>(m_distanceVal * 0.7 + m_depthImage.at<ushort>(pointxy) * 0.3);
    printf("center dist: [%d]\n", m_distanceVal);
```

however it is always printing 0 for the depth data.   Any ideas for how to fix this?

Thanks!

**Comment by DanielGuramulta** [comment]
Hello.
I was unable to reproduce your problem. For the first-frame example you don't need opencv. You could try this instead:
```cpp
int mid = fDetails.width * fDetails.height / 2;
printf("center dist:%d", data1[mid / 2]);
```
Also what is data1 pointing to, and how did you obtain it. To get the depth data in it you should use:
```cpp
uint16_t *data1;
status = frame.getData(FrameDataType::DEPTH, &data1);
```
Also make sure you call:
```cpp
camera->requestFrame(&frame);
```
before doing `getData(FrameDataType::DEPTH, &data1)` on the `frame`

**Comment by shiqli** [comment]
I have encountered similar problem on Raspberry pi. When I view the data from the first-frame program, it looks like a cropped view with on part of the frame is valid. The rest is mostly zero. See the file attached. 
[frame.zip](https://github.com/analogdevicesinc/aditof_sdk/files/4348558/frame.zip)

**Comment by dNechita** [comment]
Ok. Thanks for sharing!
