### ISSUE TITLE
Building Python bindings

### ISSUE THREAD

**Issue by mejusmajus** [analogdevicesinc/aditof_sdk#793]
I have installed the sdk as described in the readme for windos. Then I executed the given commands for creating the Python library.
https://github.com/analogdevicesinc/aditof_sdk/tree/master/bindings/python
After that I copied the aditofpython library and pasted it in the directory of the First Frame example script.
However, the library cannot be opened in the Python script.
Why can't the library be opened ? Is there anything i missed? 

Thanks in advance

**Comment by SeptimiuVana** [comment]
Hello,

Can you copy the aditof.dll/so generated next to the script as well?

**Comment by mejusmajus** [comment]
I copied all files to the sample project first frame, but the library is still not found.
![image](https://user-images.githubusercontent.com/51124729/175235283-3801d4f1-cde8-4dc8-ac7e-d01e0fab57da.png)

I did the same thing on the raspberry pi, there it worked.

**Comment by SeptimiuVana** [comment]
Did you copy aditof.dll from aditof_sdk\build\sdk\Debug as well?

If so there might be a problem with the python versions, please verify if the version used to build the adaptor is the same as the 
one you use to run the script.

**Comment by mejusmajus** [comment]
ohh thank you very much
copy the aditof.dll from aditof_sdk\build\sdk\Debug was the solution for my problem
