### ISSUE TITLE
aditofdemoview depthvalue clarification 

### ISSUE THREAD

**Issue by pras2020** [analogdevicesinc/aditof_sdk#97]
Hello All 
In "aditof_sdk/examples/aditof-demo/aditofdemoview.cpp"  in line 535 

  m_distanceVal * 0.7 + m_depthImage.at<ushort>(pointxy) * 0.3);

why the depth values are multiplied with 0.3 and why distance value multiplied by 0.7.

Regards
Prashanth R

**Comment by acozma** [comment]
This is just an averaging filter to reduce the variation of the displayed distance.
